#   Charity Funding Report

## Overview of the analysis: Explain the purpose of this analysis.

To design binary classifier using deep learning algorithm that is capable of predicting whether applicants will be successful if funded by Alphabet Soup.


## Data Preprocessing

1. What variable(s) are considered the target(s) for your model?
- The target variable is IS_SUCCESSFUL

2. What variable(s) are considered to be the features for your model?
- The rest the variables are feature variables except Name and EIN

3. What variable(s) are neither targets nor features, and should be removed from the input data?
-  Name and EIN

## Compiling, Training, and Evaluating the Model

1. How many neurons, layers, and activation functions did you select for your neural network model, and why?
- Totally I used 231 neuron in 3 hidden layers
- For internal layer I used Relu , but for final layer since its classification problem I used sigmoid.

2. Were you able to achieve the target model performance?
- I was not able to increse the accuracy more than 74%

3. What steps did you take to try and increase model performance?
- I tried to increase the neuron, hidden layer and epoch





## Summary: Summarize the overall results of the deep learning model. Include a recommendation for how a different model could solve this classification problem, and explain your recommendation.
    
- Here I utilized simple deep learning model for classification problem with 74 % accuracy.Deep learning is efficient when we have huge data.
- Since our dataset is not huge, given a chance I would have tried XG Boost classifier to solve this problem, as its effiencient model since it gives more importance when predictor is misclassified

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE

application_df.drop(columns=['EIN', 'NAME'], axis = 1, inplace = True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE

count = application_df['APPLICATION_TYPE'].value_counts()
count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(count[count < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE

count_c = application_df['CLASSIFICATION'].value_counts()
count_c

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1900        1
C6100        1
C1728        1
C1283        1
C3700        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

count_c[count_c > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C4100        6
C2400        6
C1257        5
C1600        5
C0           3
C1260        3
C2710        3
C1246        2
C3200        2
C1267        2
C1256        2
C1234        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(count_c[count_c < 1800].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

application_df = pd.get_dummies(application_df, drop_first=True)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,1,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
4,1,142590,1,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0

In [10]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE

X = application_df.drop(['IS_SUCCESSFUL'], axis = 1).values
y = application_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=18, stratify=y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE


input_features = len(X_train[0])
nn = tf.keras.models.Sequential()
# First hidden layer
#  YOUR CODE GOES HERE

nn.add(
    tf.keras.layers.Dense(units=100, input_dim=input_features, activation="relu")
)

# Second hidden layer
#  YOUR CODE GOES HERE

nn.add(tf.keras.layers.Dense(units=80, activation="relu"))

# Third hidden layer
#  YOUR CODE GOES HERE

nn.add(tf.keras.layers.Dense(units=50, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 100)               3700

 dense_5 (Dense)             (None, 80)                8080

 dense_6 (Dense)             (None, 50)                4050

 dense_7 (Dense)             (None, 1)                 51

=================================================================
Total params: 15,881
Trainable params: 15,881
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
#  YOUR CODE GOES HERE

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [19]:
# Train the model
#  YOUR CODE GOES HERE

fit_model = nn.fit(X_train_scaled, y_train, epochs=150)

Epoch 1/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5725 - accuracy: 0.7207
Epoch 2/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5571 - accuracy: 0.7296
Epoch 3/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5539 - accuracy: 0.7308
Epoch 4/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5520 - accuracy: 0.7317
Epoch 5/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5503 - accuracy: 0.7327
Epoch 6/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5499 - accuracy: 0.7332
Epoch 7/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7327
Epoch 8/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7344
Epoch 9/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7337
Epoch 10/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7319: 0s -
Epoch 11/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7347
Epoch 12/150
804/804 [==============================] - ETA: 0s - loss: 0.5464 - accuracy: 0.7342 ETA: 0s - loss: 0.5386 - accuracy: 0.74 - ETA: 0s - los - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7348
Epoch 13/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7357
Epoch 14/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7360
Epoch 15/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7362
Epoch 16/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7359: 0s - loss: 0.5456 - accuracy:
Epoch 17/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7354: 0s -
Epoch 18/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7356: 0s - - ETA: 0s - loss: 0.5433 - accuracy: 0.
Epoch 19/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7362
Epoch 20/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7375
Epoch 21/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7366
Epoch 22/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7369: 0s - loss: 0.5437 - ac
Epoch 23/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7368
Epoch 24/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7368
Epoch 25/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7376
Epoch 26/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7380
Epoch 27/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7386
Epoch 28/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7374: 0s - loss: 0.5 - ETA: 0s - loss: 0.5380 - accura
Epoch 29/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7381: 0s -
Epoch 30/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7384
Epoch 31/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7380: 0s - loss: 0.5395 - accuracy - ETA: 0s - loss: 0.5399 - accuracy: 0.
Epoch 32/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7380
Epoch 33/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7384
Epoch 34/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7384
Epoch 35/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7384: 0s - loss: 0.5393 - accuracy
Epoch 36/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7384
Epoch 37/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7392: 0s - loss: 0.537
Epoch 38/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7391
Epoch 39/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7394
Epoch 40/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7389
Epoch 41/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7388
Epoch 42/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7388
Epoch 43/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7392
Epoch 44/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7397
Epoch 45/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7388
Epoch 46/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7397: 0s - loss: 0.5372 - accuracy: 0.73
Epoch 47/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7397
Epoch 48/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7394
Epoch 49/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7390: 0s - loss: 0.5 - ETA: 0s - loss: 0.5370 - accuracy: 0.73
Epoch 50/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7396
Epoch 51/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7392: 0s - loss: 0.5347 - ac
Epoch 52/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7398
Epoch 53/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7392: 0s - loss: - ETA: 0s - loss: 0.5373 - accuracy:
Epoch 54/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7402: 0s - loss: 0.534
Epoch 55/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7399
Epoch 56/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7404
Epoch 57/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7394
Epoch 58/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7395: 0s - loss: 0.5376 - ac
Epoch 59/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5355 - accuracy: 0.7404
Epoch 60/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7403
Epoch 61/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7404: 0s - loss: 0.534 - ETA: 0s - loss: 0.5378 - accuracy
Epoch 62/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5360 - accuracy: 0.7401
Epoch 63/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5351 - accuracy: 0.7399
Epoch 64/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5352 - accuracy: 0.7405
Epoch 65/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7406: 0s - loss: 0.5325 -
Epoch 66/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5351 - accuracy: 0.7402: 0s - loss: 0.5365 - accu
Epoch 67/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5349 - accuracy: 0.7407: 0s - loss: 0.5335 - accuracy - ETA: 0s - loss: 0.5352 - accuracy: 0.74
Epoch 68/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7401
Epoch 69/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5347 - accuracy: 0.7407
Epoch 70/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5352 - accuracy: 0.7403
Epoch 71/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7401
Epoch 72/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5347 - accuracy: 0.7398: 1s - loss: 0 - ETA: 0s - loss: 0.5325
Epoch 73/150

804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7402: 0s - loss: 0.5338 - accuracy - ETA: 0s - loss: 0.5322
Epoch 74/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7404: 0s - l
Epoch 75/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7404
Epoch 76/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7402: 0s - loss: 0
Epoch 77/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7404: 0s - loss: 0.5359
Epoch 78/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7397: 0s
Epoch 79/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7398
Epoch 80/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7400: 0s - loss: 0.5341 - accu
Epoch 81/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7407
Epoch 82/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7401: 0s - los
Epoch 83/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7409: 0s - l
Epoch 84/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7406
Epoch 85/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7403
Epoch 86/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7412
Epoch 87/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7413
Epoch 88/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7412
Epoch 89/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7402: 0s - loss: 0.5340 - accuracy: 0.
Epoch 90/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7401: 0s - loss: 0
Epoch 91/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7412
Epoch 92/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7407
Epoch 93/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7403: 0s - loss: 0.5 - ETA: 0s - loss: 0.5332 - accuracy
Epoch 94/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7412
Epoch 95/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7410
Epoch 96/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7406
Epoch 97/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7407
Epoch 98/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7416
Epoch 99/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7407
Epoch 100/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7404
Epoch 101/150
804/804 [==============================] - ETA: 0s - loss: 0.5349 - accuracy: 0.7396 ETA: 0s - loss: 0.5364 - ac - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7407
Epoch 102/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7411
Epoch 103/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7412: 0s - loss: 0.533
Epoch 104/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7413: 0s - loss: 0.5303 - accura
Epoch 105/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7410
Epoch 106/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7408
Epoch 107/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7408
Epoch 108/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7413: 0s - los
Epoch 109/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7409: 0s - loss: 0 - ETA: 0s - loss: 0.5325 - accuracy:
Epoch 110/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7413
Epoch 111/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7406
Epoch 112/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7418: 0s - loss: 0.5
Epoch 113/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7411: 0s - los - ETA: 0s - loss: 0.5354 - accuracy
Epoch 114/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7411: 0s - loss: 0.5318 - accura
Epoch 115/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7414
Epoch 116/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7414: 0s - loss: 0.5324 - accuracy: 0.
Epoch 117/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7411: 0s - loss: 0.5306 -
Epoch 118/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7411
Epoch 119/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7415: 0s - loss: - ETA: 0s - loss: 0.5338 - accuracy
Epoch 120/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7410
Epoch 121/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5319 - accuracy: 0.7416
Epoch 122/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7414: 1s - l - ETA: 0s - loss: 0.5332 - accura
Epoch 123/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7414
Epoch 124/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7416
Epoch 125/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7414
Epoch 126/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7409
Epoch 127/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7412: 0s - loss: 0.5312 - accu
Epoch 128/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7416
Epoch 129/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7413
Epoch 130/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7410: 0s - l
Epoch 131/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7413
Epoch 132/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7411: 0s - loss: 0.5271 - accura - ETA: 0s - loss: 0.531
Epoch 133/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7411
Epoch 134/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7411: 0s - loss: 0.529 - ETA: 0s - loss: 0.5327 - accuracy:
Epoch 135/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7414: 0s - loss: 0.5341 - accuracy: 0.74 - ETA: 0s -
Epoch 136/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7409
Epoch 137/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7409
Epoch 138/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7416
Epoch 139/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7416
Epoch 140/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7411: 0s - loss:
Epoch 141/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7414: 0s - loss: 0.5276
Epoch 142/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7415: 0s - loss: 0.5297 - accuracy - ETA: 0s - loss: 0.5324 - accuracy: 0.
Epoch 143/150

804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7418
Epoch 144/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7424: 0s
Epoch 145/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7411
Epoch 146/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7412
Epoch 147/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7418: 0s - loss: 0.5311 - accura
Epoch 148/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7416
Epoch 149/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7415
Epoch 150/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7416: 0s - loss: 0.5370 - accuracy: 0.

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5955 - accuracy: 0.7282 - 347ms/epoch - 1ms/step
Loss: 0.5954578518867493, Accuracy: 0.7281632423400879

In [22]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE

nn.save('Charity-funding.h5')